export function embed(pkg: string) {
	return `
package ${pkg}

import (
	"embed"

	"github.com/nichady/golte"
)

//go:embed */**
var fsys embed.FS

// Golte is the main middleware to register to your router. It generated by the build step.
var Golte = golte.New(fsys)
	`;
};
